server:
  port: 5454
#  servlet:
#    context-path: /crud

spring:
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
    url: jdbc:h2:mem:tododb